name: Build Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Swift
      uses: fwal/setup-swift@d43a564349d1341cd990cfbd70d94d63b8899475
      with:
        swift-version: "5.7"
    - name: Build
      run: swift build
  build-linux:
    runs-on: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install \
          binutils \
          git \
          gnupg2 \
          libc6-dev \
          libcurl4 \
          libedit2 \
          libgcc-9-dev \
          libpython2.7 \
          libsqlite3-0 \
          libstdc++-9-dev \
          libxml2 \
          libz3-dev \
          pkg-config \
          tzdata \
          uuid-dev \
          zlib1g-dev
      - name: Setup Swift
        uses: fwal/setup-swift@d43a564349d1341cd990cfbd70d94d63b8899475
        with:
          swift-version: "5.7"
      - name: Build
        run: swift build
